spring:
  application:
    name: feign

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#暴露 hystrix.stream 端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
#feign + hystrix 降级,feign 默认没有启用 hystrix
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

item-service:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    ConnectTimeout: 1000
    ReadTimeout: 500